# Generated by Django 4.2.6 on 2023-11-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_picture_waterintake_macro_dayweight_daymacro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Client'), (2, 'Coach'), (3, 'Admin')], null=True),
        ),
    ]
