# Generated by Django 4.2.6 on 2023-11-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintake',
            name='WaterCup_250ml',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
