# Generated by Django 4.2.6 on 2023-11-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_waterintake_watercup_250ml'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterIntake',
        ),
    ]
