# Generated by Django 4.2.6 on 2023-11-02 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diet', '0003_diet_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='diet',
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diet.diet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diet.diet')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diet.meal')),
            ],
        ),
    ]
