# Generated by Django 4.2.6 on 2023-11-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0008_dailymeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diet.meal'),
        ),
    ]
