# Generated by Django 4.2.6 on 2023-12-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0003_userproxy_alter_userworkout_user'),
        ('Diet', '0010_alter_dailymeal_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.userproxy'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='Workout.userproxy'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.userproxy'),
        ),
    ]
